### ISSUE TITLE
Who are you?

### ISSUE THREAD

**Issue by sergiobd** [LibofRelax/9-Axis-IMU-Tracking#1]
What a wonderfully clean code.
Who are you? Is this code part of a class?
If so, are some other materials (e.g. syllabus, books) available?

**Comment by john2zy** [comment]
I'm just an undergrad student 😂. This is a personal project which happened to be used as prototype in my internship. The included references (especially "Using Inertial Sensors....") should be sufficient for implementing EKF. Although I didn't completely understand the math involved. To the best of my knowledge, if you really want a better algorithm, check [Madgwick](https://x-io.co.uk/open-source-imu-and-ahrs-algorithms/) out. His demos are unreal.

I also found this [Blog](https://nitinjsanket.github.io/tutorials/attitudeest/madgwick)! Unfortunately my math is very poor, I don't know how to implement this.
