### ISSUE TITLE
which sensors should be logged in the HyperIMU app

### ISSUE THREAD

**Issue by rielt12** [LibofRelax/9-Axis-IMU-Tracking#11]
Hello,

I was confused which sensors should be logged in the hyperIMU app.
![WhatsApp Image 2024-02-27 at 16 20 39_47378dca](https://github.com/LibofRelax/IMU-Position-Tracking/assets/13559351/74643b7a-daee-47bc-8d59-5253d47629de)

Thanks

**Comment by john2zy** [comment]
You want accelerometer, gyroscope, and magnetometer. Calibrated/Uncalibrated doesn't make a big difference.
