### ISSUE TITLE
6 degree of freedom IMU 

### ISSUE THREAD

**Issue by lfxx** [LibofRelax/9-Axis-IMU-Tracking#3]
What if i want to process 6 degree of freedom IMU data,what should i do?

**Comment by john2zy** [comment]
I don't think that's possible because acceleration data includes gravity, you need magnetometer to remove this part of acceleration.

**Comment by lfxx** [comment]
> I don't think that's possible because acceleration data includes gravity, you need magnetometer to remove this part of acceleration.

也就是说，只有六自由度IMU的话，从理论上来说是不能算出位置的吗？确实，我现在只找到六自由度算姿态的。有加速度的双重积分应该是可以算出位置的啊

**Comment by john2zy** [comment]
加速度计通过测量一个质量块的形变来计算加速度，所以加速度计无法区分由加速度产生的形变和重力产生的形变，需要用地磁方向来大致消除重力的分量。如果给数据加上重力方向不变的约束，并将重力分量从加速度数据里消除，确实可以用加速度和角速度计算位置。

**Comment by lfxx** [comment]
就是说Z方向加速度在没有地磁变量作为辅助的话基本是不能用的是吧，如果我们认为物体不会沿着Z轴运动的话，把Z轴加速度置零就行了吧-------- 原始邮件 --------发件人： John ***@***.***>日期： 2021年8月28日周六 15:05收件人： LibofRelax/IMU-Position-Tracking ***@***.***>抄送： 高峰 ***@***.***>, Author ***@***.***>主    题： Re: [LibofRelax/IMU-Position-Tracking] 6 degree of freedom IMU  (#3)
加速度计通过测量一个质量块的形变来计算加速度，所以加速度计无法区分由加速度产生的形变和重力产生的形变，需要用地磁方向来大致消除重力的分量。如果给数据加上重力方向不变的约束，并将重力分量从加速度数据里消除，确实可以用加速度和角速度计算位置。

**Comment by john2zy** [comment]
是的，但我觉得不太实际

**Comment by JasonTang84** [comment]
> 就是说Z方向加速度在没有地磁变量作为辅助的话基本是不能用的是吧，如果我们认为物体不会沿着Z轴运动的话，把Z轴加速度置零就行了吧-------- 原始邮件 --------发件人： John ***@***.***>日期： 2021年8月28日周六 15:05收件人： LibofRelax/IMU-Position-Tracking ***@***.***>抄送： 高峰 ***@***.***>, Author ***@***.***>主 题： Re: [LibofRelax/IMU-Position-Tracking] 6 degree of freedom IMU (#3) 加速度计通过测量一个质量块的形变来计算加速度，所以加速度计无法区分由加速度产生的形变和重力产生的形变，需要用地磁方向来大致消除重力的分量。如果给数据加上重力方向不变的约束，并将重力分量从加速度数据里消除，确实可以用加速度和角速度计算位置。 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

我也想通过6轴数据计算位置，后面你解决了吗？

**Comment by MarkZXZX** [comment]
六轴如果可以得到稳定的四元数，借助四元数计算出重力加速度在不同的轴上面的分量，请问能不能做到九轴的效果
