### ISSUE TITLE
Can 6 DoF IMU use this codes?

### ISSUE THREAD

**Issue by Ceciliammm** [LibofRelax/9-Axis-IMU-Tracking#4]
I have an IMU with 6 DoF （Accelerator anf gyroscope）, but this project is designed for 9 DoF IMU.
I want to know that whether it can deal with 6 DoF IMU's position tracking. 
If it can do this job, How can I set the values of magnetometer?

**Comment by john2zy** [comment]
That would be impossible in my opinion. Without the magnetometer, you won't be able to determine gravity.
