### ISSUE TITLE
I implement your test and can not track my position

### ISSUE THREAD

**Issue by 11721206** [LibofRelax/9-Axis-IMU-Tracking#5]
Hello, i use hyperimu to pull (uncalibrated) data from my phone, set the data order in your code , when I plot my tracjectory and position, I found the plotted position in figure do not match the real positon. Is it availble to post your data and result plot？ Thank you

**Comment by john2zy** [comment]
Mine was super inaccurate too. It could read out a square of half a meter at best.

Unfortunately, I'm not good enough at math to determine if it's a mistake in the algorithm or caused by intrinsic noise.
