### ISSUE TITLE
ASK FOR IMU DATA

### ISSUE THREAD

**Issue by wang338** [LibofRelax/9-Axis-IMU-Tracking#6]
Sorry to bother you, I would like to ask if you can send a copy of IMU data. Although you mentioned in read me that you can download data from HyperIMU through TCP, unfortunately, my google play has been banned now, （cause I am in CHN）so I can't get the app.  I would like to ask if you can provide a copy of IMU data.Thank you very much.

**Comment by john2zy** [comment]
Unfortunately, it's long gone. Please try to gain access yourself.

**Comment by ProcedureJing** [comment]
you can search hyperIMU.apk on google and install the app on your android phone
