### ISSUE TITLE
Units of "data"

### ISSUE THREAD

**Issue by uip-486** [LibofRelax/9-Axis-IMU-Tracking#9]
Hello, your code gives me a good reference meaning, but after reading the code, I still have a question, that is, what are the units of angular velocity, acceleration, and magnetic declination as input data, and the units of output data of different sensors are different, so the data needs to be converted in advance. Can you please answer that?

**Comment by john2zy** [comment]
Sorry, I can't recall. Can you check the android app I used?

**Comment by uip-486** [comment]
Thanks for the reply, I'll give it a try。
